#!/usr/bin/env python3
"""Strata index generator and constitution auditor.

Usage: python3 encyclopedia/tools/encyc.py [--check-only]

Walks encyclopedia/**/*.md (excluding METHOD/INDEX/NEXT), parses frontmatter,
audits the invariants of METHOD.md, and regenerates INDEX.md.
Exit code 1 if any audit violation is found.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDE = {"METHOD.md", "INDEX.md", "NEXT.md"}
STATES = ["stub", "sketch", "survey", "article", "deep"]
CLASSES = {"anchor", "standard", "satellite"}
DIVISIONS = ["logic", "metaphysics", "epistemology", "mind", "language",
             "science", "ethics", "politics", "aesthetics", "religion"]
REGISTERS = ["figures", "traditions", "meta"]

STUB_RE = re.compile(r"^- `([a-z0-9-]+)` — \*\*(.+?)\*\* — (.+?) \*\((anchor|standard|satellite)\)\*")


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None, text, "missing frontmatter"
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip() for x in v[1:-1].split(",") if x.strip()]
        fm[k.strip()] = v
    return fm, m.group(2), None


def main():
    check_only = "--check-only" in sys.argv
    nodes, errors = {}, []

    for path in sorted(ROOT.rglob("*.md")):
        if path.name in EXCLUDE or "tools" in path.parts:
            continue
        fm, body, err = parse(path)
        rel = path.relative_to(ROOT)
        if err:
            errors.append(f"{rel}: {err}")
            continue
        for key in ("node", "title", "state", "class", "parent", "layer"):
            if key not in fm:
                errors.append(f"{rel}: missing frontmatter key '{key}'")
        node = fm.get("node", "")
        if fm.get("state") not in STATES[1:]:
            errors.append(f"{rel}: invalid state '{fm.get('state')}' (files are sketch+; stubs have no file)")
        if fm.get("class") not in CLASSES:
            errors.append(f"{rel}: invalid class '{fm.get('class')}'")
        # node must match file location
        top = node.split(".")[0]
        expect = ROOT / top / (node + ".md") if top in DIVISIONS else ROOT / path.parent.name / (path.stem + ".md")
        if top in DIVISIONS and path != expect:
            errors.append(f"{rel}: node '{node}' does not match path (expected {expect.relative_to(ROOT)})")
        stubs = [m.groups() for line in body.splitlines() if (m := STUB_RE.match(line.strip()))]
        nodes[node if top in DIVISIONS else f"{path.parent.name}.{path.stem}" if path.parent.name in REGISTERS and path.stem != path.parent.name else node] = {
            "node": node, "fm": fm, "path": rel, "words": len(body.split()), "stubs": stubs,
        }

    # parent existence + state invariant
    by_node = {v["fm"]["node"]: v for v in nodes.values()}
    for v in nodes.values():
        fm = v["fm"]
        parent = fm.get("parent", "")
        if parent == "root":
            continue
        p = by_node.get(parent)
        if not p:
            errors.append(f"{v['path']}: parent '{parent}' has no file")
            continue
        if STATES.index(fm["state"]) > STATES.index(p["fm"]["state"]):
            errors.append(f"{v['path']}: state '{fm['state']}' exceeds parent '{parent}' state '{p['fm']['state']}'")

    # ---- report ----
    n_files = len(nodes)
    n_stubs = sum(len(v["stubs"]) for v in nodes.values())
    n_words = sum(v["words"] for v in nodes.values())
    print(f"audit: {n_files} articles, {n_stubs} stubs, {n_words} words, {len(errors)} violation(s)")
    for e in errors:
        print(f"  VIOLATION {e}")

    if not check_only:
        write_index(by_node, n_files, n_stubs, n_words)
        print(f"wrote {ROOT / 'INDEX.md'}")
    return 1 if errors else 0


def badge(state):
    return {"sketch": "◔", "survey": "◑", "article": "◕", "deep": "●"}.get(state, "·")


def write_index(by_node, n_files, n_stubs, n_words):
    out = ["# Strata — Index", "",
           "Generated by `tools/encyc.py`; do not edit by hand. States: ◔ sketch ◑ survey ◕ article ● deep · stub.",
           "",
           f"**{n_files} articles · {n_stubs} stubs · {n_words:,} words**", ""]

    def emit(node, depth):
        v = by_node.get(node)
        if not v:
            return
        fm = v["fm"]
        pad = "  " * depth
        out.append(f"{pad}- {badge(fm['state'])} [**{fm['title']}**]({v['path']}) — {fm['state']}, {fm['class']}, {v['words']:,}w")
        kids = [s for s, *_ in v["stubs"]]
        for slug, title, gloss, cls in v["stubs"]:
            child = f"{node}.{slug}" if node not in REGISTERS else slug
            if child in by_node or (node in REGISTERS and any(x["fm"]["parent"] == node and x["fm"]["node"] == slug for x in by_node.values())):
                emit(child if child in by_node else slug, depth + 1)
            else:
                out.append(f"{'  ' * (depth + 1)}- · `{slug}` — {title} *(stub, {cls})*")

    out.append("## Divisions\n")
    for d in DIVISIONS:
        emit(d, 0)
    out.append("")
    out.append("## Registers\n")
    for r in REGISTERS:
        emit(r, 0)

    nxt = ROOT / "NEXT.md"
    if nxt.exists():
        out += ["", "## NEXT", "", nxt.read_text(encoding="utf-8").strip()]
    (ROOT / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
